# 应用程序配置
app:
  - name: ks-server
    deployment:
      image: crpi-o5e9g8vha41iltg8.cn-hangzhou.personal.cr.aliyuncs.com/ks_img/ks-server:latest
      podAnnotations: {}
      podLabels: {}
      podSecurityContext: {}
      livenessProbe:
        tcpSocket:
          port: 80
      readinessProbe:
        tcpSocket:
          port: 80        
      resources: {}
      env:
        - name: TZ
          value: Asia/Shanghai
        - name: LANG
          value: C.UTF-8
        - name: GIN_MODE
          value: release
        - name: LOG_LEVEL
          value: info
        - name: USERNAME
          value: Admin
        - name: PASSWORD
          value: Admin123
        - name: INCLUSTER
          value: "true"
        - name: METADATA_NAMESPACE
          value: ks
        - name: PORT
          value: ":80"
    service:
      type: ClusterIP
      port: 80
    ingress:
      enabled: true
      className: "nginx"
      annotations: {}
      hosts:
        - host: ks-server.tpass.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
  - name: ks-web
    deployment:
      image: crpi-o5e9g8vha41iltg8.cn-hangzhou.personal.cr.aliyuncs.com/ks_img/ks-web:v1.0
      podAnnotations: {}
      podLabels: {}
      podSecurityContext: {}
      livenessProbe:
        tcpSocket:
          port: 80        
      readinessProbe:
        tcpSocket:
          port: 80        
      resources: {}
      env:
        - name: TZ
          value: Asia/Shanghai
        - name: LANG
          value: C.UTF-8      
    service:
      type: ClusterIP
      port: 80
    ingress:
      enabled: true
      className: "nginx"
      annotations: {}
      hosts:
        - host: ks-web.tpass.local
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: []
# 全局配置
global:
  replicaCount: 1
  image:
    pullPolicy: Always
  imagePullSecrets: []
  serviceAccount:
    create: true
    automount: true
    annotations: {}
    name: ""
  nodeSelector: {}
  tolerations: []
  affinity: {}
  roleBinding:
    create: true
  ingress:
    enabled: true
    className: "nginx"
    annotations: {}
    host: ks.tpass.local
    paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: svc-ks-web
            port:
              number: 80
      - path: /api
        pathType: ImplementationSpecific
        backend:
          service:
            name: svc-ks-server
            port:
              number: 80
    tls: []
