{{- range .Values.app}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .deployment.name }}
  labels:
    dpName: {{ .deployment.name }}
    {{- include "ks.labels" $ | nindent 4 }}
spec:
  replicas: {{ $.Values.global.replicaCount }}
  selector:
    matchLabels:
      dpName: {{ .deployment.name }}
      {{- include "ks.labels" $ | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- toYaml .deployment.podAnnotations | nindent 8 }}
      labels:
        dpName: {{ .deployment.name }}
        {{- include "ks.labels" $ | nindent 8 }}
    spec:
      imagePullSecrets:
        {{- toYaml $.Values.global.imagePullSecrets | nindent 8 }}
      serviceAccountName: {{ $.Values.global.serviceAccount.name }}
      containers:
        - name: {{ .name }}
          image: {{ .deployment.image }}
          imagePullPolicy: {{ $.Values.global.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .service.port }}
              protocol: TCP
          env:
            {{- range .deployment.env }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
          livenessProbe:
            {{- toYaml .deployment.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .deployment.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .deployment.resources | nindent 12 }}        
{{- end}}
