# 使用基础镜像
FROM crpi-o5e9g8vha41iltg8.cn-hangzhou.personal.cr.aliyuncs.com/ks_required/alpine:3.20
# 配置登录用户名、密码、程序启动端口号
ENV KUBECONFIGPATH=/app/kubeconfig
ENV USERNAME=Admin
ENV PASSWORD=Admin123
ENV PORT=:8080
# 设置工作目录
WORKDIR /app
# 准备程序文件
COPY ks-server-linux-x86 /app/ks-server
COPY ./config/baseKubeConfig /app/kubeconfig
# 设置可执行权限
RUN chmod +x /app/ks-server
# 设置默认入口点（启动时执行 ./ks-server）
ENTRYPOINT [ "./ks-server" ]