---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ks-server
  name: ks-server
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: ks-server
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ks-server
  name: ks-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ks-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ks-server
    spec:
      restartPolicy: Always
      serviceAccountName: ks-server
      containers:
        - name: container-0
          ports:
            - name: web
              containerPort: 8080
              protocol: TCP
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: LANG
              value: C.UTF-8
            - name: GIN_MODE
              value: release
            - name: LOG_LEVEL
              value: info
            - name: USERNAME
              value: Admin
            - name: PASSWORD
              value: Admin123
            - name: INCLUSTER
              value: "true"
            - name: METADATA_NAMESPACE
              value: ks
          image: crpi-o5e9g8vha41iltg8.cn-hangzhou.personal.cr.aliyuncs.com/ks_required/ks-server:v1.4
          lifecycle: {}
          livenessProbe:
            failureThreshold: 2
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 2
          readinessProbe:
            failureThreshold: 2
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 2
          resources:
            limits:
              cpu: 1
              memory: 1024Mi
            requests:
              cpu: 200m
              memory: 256Mi
